ads/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.ads, name='ads'),
    path('ads_detail/<slug:ads_slug>/', views.ads_detail, name='ads_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('place_order/', views.place_order, name='place_order'),
    # path('payments/', views.payments, name='payments'),

]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

carts/models.py
from accounts.models import Account
from store.models import *


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True, verbose_name='ایدی سبد خرید')
    date_added = models.DateField(auto_now_add=True, verbose_name='تاریخ اضافه شدن به سبد خرید')

    def __str__(self):
        return self.cart_id

    class Meta:
        verbose_name = 'اطلاعات سبد خرید'
        verbose_name_plural = 'اطلاعات سبد خرید'


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, verbose_name='کاربر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    variations = models.ManyToManyField(Variation, blank=True, verbose_name='انتخاب شده')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, verbose_name='سبد خرید')
    quantity = models.IntegerField(verbose_name='موجودی')
    is_active = models.BooleanField(default=True, verbose_name='فعال')

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبد خرید'

carts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from carts.models import Cart, CartItem
from store.models import Product, Variation
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)  # get the product
    # If the user is authenticated
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                user=current_user,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:cart')
    # If the user is not authenticated
    else:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]

                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key,
                                                      variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))  # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(
                cart_id=_cart_id(request)
            )
        cart.save()

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            # existing_variations -> database
            # current variation -> product_variation
            # item_id -> database
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variations.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()

            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    item.variations.clear()
                    item.variations.add(*product_variation)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity=1,
                cart=cart,
            )
            if len(product_variation) > 0:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
            cart_item.save()
        return redirect('carts:cart')


def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass

    return redirect('carts:cart')


def cart(request, total=0, quantity=0, cart_items=None):
    global grand_total

    try:
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        grand_total = total
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'grand_total': grand_total,

    }
    return render(request, 'cart/cart.html', context)


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('carts:cart')


@login_required(login_url='account:login')
def checkout(request, total=0, quantity=0, cart_items=None):
    global grand_total
    try:
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        grand_total = total
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'grand_total': grand_total,
    }
    return render(request, 'cart/checkout.html', context)

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load humanize %}
{% load persian_number %}
{% load static %}
{% block title %} سبد خرید | تک کا مارکت {% endblock %}
{% block content %}
    <section class="section-content padding-y bg new-font">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->
            {% if not cart_items %}
                <h2 class="text-center"> سبد خرید شما خالی است </h2>
                <br>
                <div class="text-center">
                    <a href="{% url 'store:store' %}" class="btn btn-primary"> ادامه خرید </a>
                </div>
            {% else %}
                <div class="row">
                    <aside class="col-lg-9">
                        <div class="card">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">محصول</th>
                                    <th scope="col" width="120">تعداد</th>
                                    <th scope="col" width="120">قیمت</th>
                                    <th scope="col" class="text-right" width="200"></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for cart_item in cart_items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ cart_item.product.image.url }}"
                                                                        class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="{{ cart_item.product.get_url }}"
                                                       class="title text-dark">{{ cart_item.product.product_name | persianize_digits }}</a>
                                                    <p class="text-muted small">
                                                        {% if  cart_item.variations.all %}
                                                            {% for item in cart_item.variations.all %}
                                                                {{ item.variation_category | capfirst }} :
                                                                {{ item.variation_value | capfirst }} <br>
                                                            {% endfor %}
                                                        {% endif %}
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <!-- col.// -->
                                            <div class="col">
                                                <div class="input-group input-spinner">
                                                    <div class="input-group-prepend">
                                                        <a href="{% url 'carts:remove_cart' cart_item.product.id cart_item.id %}"
                                                           class="btn btn-light" type="button" id="button-plus"><i
                                                                class="fa fa-minus"></i></a>
                                                    </div>
                                                    <input type="text" class="form-control"
                                                           value="{{  cart_item.quantity  }}">
                                                    <div class="input-group-append">
                                                        <form action="{% url 'carts:add_cart' cart_item.product.id %}"
                                                              method="post">
                                                            {% csrf_token %}
                                                            {% for item in cart_item.variations.all %}
                                                                <input type="hidden"
                                                                       name="{{ item.variation_category | lower }}"
                                                                       value="{{ item.variation_value | capfirst }}">
                                                            {% endfor %}
                                                            <button
                                                                    class="btn btn-light" type="submit"
                                                                    id="button-minus"><i
                                                                    class="fa fa-plus"></i></button>
                                                        </form>
                                                    </div>
                                                </div>
                                                <!-- input-group.// -->
                                            </div> <!-- col.// -->
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price"> {{ cart_item.sub_total |  persian_int | intcomma:False }}</var>
                                                <small class="text-muted">
                                                    تومان {{ cart_item.product.price |  persian_int | intcomma:False }}
                                                    هر محصول </small>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <a href="{% url 'carts:remove_cart_item' cart_item.product.id cart_item.id %}"
                                               onclick="return confirm('ایا مطمئن هستید برای کم کردن / حذف محصول؟')"
                                               class="btn btn-danger"> حذف </a>
                                        </td>

                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->
                    <aside class="col-lg-3">

                        <div class="card">
                            <div class="card-body">
                                <dl class="dlist-align">
                                    <dt>قیمت کل محصول:</dt>
                                    <dd class="text-right new-font">
                                        تومان{{ total |intcomma:False | persianize_digits }}</dd>
                                </dl>
                                <dl class="dlist-align">
                                    <dt>قیمت کل :</dt>
                                    <dd class="text-right text-dark b">
                                        <strong class="new-font">تومان{{ grand_total |  intcomma:False | persianize_digits }}  </strong>
                                    </dd>
                                </dl>
                                <hr>
                                <p class="text-center mb-3">
                                    <img src="{% static 'template/images/WhatsApp-Emblem.png' %}" height="60">
                                </p>
                                <a href="{% url 'carts:checkout' %}" class="btn btn-primary btn-block"> ادامه خرید </a>
                                <a href="{% url 'store:store' %}" class="btn btn-light btn-block"> فروشگاه </a>
                            </div> <!-- card-body.// -->
                        </div> <!-- card.// -->

                    </aside> <!-- col.// -->


                </div> <!-- row.// -->
            {% endif %}

            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>
{% endblock %}

templates/cart/checkout.html
{% extends 'base/base.html' %}
{% load humanize %}
{% load persian_number %}
{% load static %}
{% block title %} ادامه خرید | تک کا مارکت {% endblock %}
{% block content %}
    <section class="section-content padding-y bg new-font">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->

            <div class="row">
                <aside class="col-lg-6">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title mb-4" style="text-align: right;">مشخصات</h4>
                            <form action="{% url 'orders:place_order' %}" method="POST"
                                  style="text-align: right;direction: rtl;">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">نام</label>
                                        <input type="text" name="first_name" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">نام خانوادگی</label>
                                        <input type="text" name="last_name" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">ایمیل</label>
                                        <input type="email" name="email" class="form-control">
                                    </div>
                                    <div class="col form-group">
                                        <label for="">شماره همراه</label>
                                        <input type="text" name="phone" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">ادرس </label>
                                        <input type="text" name="address_line_1" class="form-control">
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col form-group">
                                        <label for="">کوچه</label>
                                        <input type="text" name="state" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">شهر</label>
                                        <input type="text" name="city" class="form-control" required>
                                    </div>
                                    <div class="col form-group">
                                        <label for="">کشور</label>
                                        <input type="text" name="country" class="form-control" required>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <label for="">یادداشت</label>
                                    <textarea name="order_note" rows="2" class="form-control"></textarea>
                                </div>
                        </div>


                    </div> <!-- card.// -->

                </aside> <!-- col.// -->
                <aside class="col-lg-6">

                    <div class="card">
                        <div class="card-body">
                            <table class="table table-borderless table-shopping-cart">
                                <thead class="text-muted">
                                <tr class="small text-uppercase">
                                    <th scope="col">محصول</th>
                                    <th scope="col" width="120">تعداد</th>
                                    <th scope="col" width="120">قیمت</th>

                                </tr>
                                </thead>
                                <tbody>

                                {% for cart_item in cart_items %}
                                    <tr>
                                        <td>
                                            <figure class="itemside align-items-center">
                                                <div class="aside"><img src="{{ cart_item.product.image.url }}"
                                                                        class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="{{ cart_item.product.get_url }}"
                                                       class="title text-dark">{{ cart_item.product.product_name |  persianize_digits }}</a>
                                                    <p class="text-muted small">
                                                        {% if cart_item.variations.all %}
                                                            {% for item in cart_item.variations.all %}
                                                                {{ item.variation_category | capfirst }} :
                                                                {{ item.variation_value | capfirst }} <br>
                                                            {% endfor %}
                                                        {% endif %}
                                                    </p>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <!-- col.// -->
                                            <label for="">{{ cart_item.quantity |   persianize_digits }}</label>
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price"> {{ cart_item.sub_total |intcomma:False | persianize_digits }}</var>
                                                <small class="text-muted">  {{ cart_item.product.price |intcomma:False | persianize_digits }}
                                                    هر
                                                    محصول </small>
                                            </div> <!-- price-wrap .// -->
                                        </td>

                                    </tr>
                                {% endfor %}

                                </tbody>
                            </table>

                            <button type="submit" name="submit" class="btn btn-primary btn-block"> تایید نهایی
                            </button>
                            <a href="{% url 'store:store' %}" class="btn btn-light btn-block">ادامه خرید</a>
                            </form>
                        </div> <!-- card-body.// -->
                    </div> <!-- card.// -->


                </aside> <!-- col.// -->


            </div> <!-- row.// -->

            <!-- ============================ COMPONENT 1 END .// ================================= -->

        </div> <!-- container .//  -->
    </section>

{% endblock %}