ads/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.ads, name='ads'),
    path('ads_detail/<slug:ads_slug>/', views.ads_detail, name='ads_detail'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

home/models.py
from django.db import models
from django.utils.html import format_html


class Slider(models.Model):
    image = models.ImageField(upload_to='photos/slider', verbose_name='اسلایدر ')

    class Meta:
        verbose_name = 'اسلایدر'
        verbose_name_plural = 'اسلایدر'

    def img(self):
        return format_html('<img src="{}" height="50" style="border-radius:50px;"/>'.format(self.image.url))

home/views.py
from django.shortcuts import render

from ads.models import Ads
from home.models import Slider
from store.models import Product


def home(request):
    ads = Ads.objects.all().filter(is_available=True).order_by('created_date')[:5]
    products = Product.objects.all().filter(is_available=True).order_by('created_date')[:5]
    slider = Slider.objects.all()
    context = {
        'products': products,
        'slider': slider,
        'ads': ads,
    }
    return render(request, 'home/index.html', context)

templates/home/index.html
{% extends 'base/base.html' %}
{% load static %}
{% load persian_number %}
{% load humanize %}
{% block content %}

    <section class="section-intro padding-y-sm">
        <div class="container slideshow-container ">
            <div class="intro-banner-wrap mySlides">
                {% for foo in slider %}
                    <img src="{{ foo.image.url }}" class="img-fluid rounded">
                {% endfor %}
            </div>
        </div>


    </section>
    <section class="section-name padding-y-sm">
        <div class="container">

            <header class="section-heading">
                <a href="{% url 'ad:ads' %}" class="btn btn-outline-primary float-right new-font">مشاهده تمام
                    اگهی </a>
                <h3 class="section-title new-font">مناسب برای کسب و کار شما </h3>
            </header>


            <div class="row">
                {% for ad in ads %}
                    <div class="col-md-3">
                        <div class="card card-product-grid">
                            <a href="{{ ad.get_url }}"
                               class="img-wrap"><img
                                    src="{{ ad.image.url }}"> </a>
                            <figcaption class="info-wrap">
                                <a href="{{ ad.get_url }}"
                                   class="title new-font"
                                   style="text-align: center;">{{ ad.ads_name }}</a>
                            </figcaption>
                        </div>
                    </div>
                {% endfor %}


            </div>

        </div>
    </section>


    <section class="section-name padding-y-sm">
        <div class="container">

            <header class="section-heading">
                <a href="{% url 'store:store' %}" class="btn btn-outline-primary float-right new-font">مشاهده تمام
                    محصولات</a>
                <h3 class="section-title new-font">محصولات محبوب</h3>
            </header>


            <div class="row">
                {% for product in products %}
                    <div class="col-md-3">
                        <div class="card card-product-grid">
                            <a href="{{ product.get_url }}"
                               class="img-wrap"><img
                                    src="{{ product.image.url }}"> </a>
                            <figcaption class="info-wrap">
                                <a href="{{ product.get_url }}"
                                   class="title new-font"
                                   style="text-align: center;">{{ product.product_name | persianize_digits }}</a>
                                <div class="price mt-1 new-font" style="text-align: center;">
                                    تومان {{ product.price | persian_int | intcomma:False }}</div>
                            </figcaption>
                        </div>
                    </div>
                {% endfor %}


            </div>

        </div>
    </section>

    <footer class="section-footer border-top new-font">
        <div class="container">
            <section class="footer-bottom border-top row">
                <div class="col-md-2">
                    <p class="text-muted"> &copy تک کا مارکت </p>
                </div>
                <div class="col-md-8 text-md-center">
                    <span class="px-2">markettakka@gmail.com</span>
                    <span class="px-2">09143520588</span>
                </div>
            </section>
        </div>
    </footer>


{% endblock %}