accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

ads/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.ads, name='ads'),
    path('ads_detail/<slug:ads_slug>/', views.ads_detail, name='ads_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

templates/base/alert.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container" style="text-align: right;direction: rtl;">
            <div{% if message.tags %} class=" alert alert-{{ message.tags }}"{% endif %}
                                      role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
                </button>
                {{ message }}</div>
        </div>
    {% endfor %}
{% endif %}

templates/base/base.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="pragma" content="no-cache"/>
    <meta http-equiv="cache-control" content="max-age=604800"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title> {% block title %} فروشگاه انلاین مصالح ساختمانی  | تک کا مارکت {% endblock %}</title>

    <link href="{% static 'template/images/favicon.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- jQuery -->
    <script src="{% static 'template/js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>

    <!-- Bootstrap4 files-->
    <script src="{% static 'template/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <link href="{% static 'template/css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'template/css/custom.css' %}" rel="stylesheet" type="text/css"/>

    <!-- Font awesome 5 -->
    <link href="{% static 'template/fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

    <!-- custom style -->
    <link href="{% static 'template/css/ui.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'template/css/responsive.css' %}" rel="stylesheet"
          media="only screen and (max-width: 1200px)"/>

    <!-- custom javascript -->
    <script src="{% static 'template/js/script.js' %}" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>



    <script type="text/javascript">
        /// some script

        // jquery ready start
        $(document).ready(function () {
            // jQuery code

        });
        // jquery end
    </script>

</head>
<body>


<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTop4">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a href="{% url 'home:home' %}" class="nav-link"> Fa </a>

                    </li>
                </ul>
                <ul class="navbar-nav new-font">
                    <li><a href="mailto:markettakka@gmail.com" class="nav-link"> <i class="fa fa-envelope"></i> ایمیل
                    </a></li>
                    <li><a href="tel:09143520588" class="nav-link"> <i class="fa fa-phone"></i> تماس با ما </a></li>
                </ul>
            </div>
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="{% url 'home:home' %}" class="brand-wrap">
                        <img class="logo" src="{% static 'template/images/logo.jpg' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
{#                        <button type="button" class="btn btn-primary dropdown-toggle new-font" data-toggle="dropdown">#}
{#                            <i class="fa fa-bars"></i> دسته بندی#}
{#                        </button>#}
                        <div class="dropdown-menu new-font">
                            <a class="dropdown-item" href="{% url 'store:store' %}"> تمامی محصولات </a>
                            {% for category in ca %}
                                <a class="dropdown-item"
                                   href="{% url 'store:products_by_category' category.slug %}">{{ category.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <a href="{% url 'store:store' %}" class="btn btn-outline-primary new-font">فروشگاه</a>
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form action="{% url 'store:search' %}" class="search" method="GET">
                        <div class="input-group w-100">
                            <input type="text" class="form-control new-font" style="width:60%;text-align: right;"
                                   placeholder="جستجو"
                                   name="keyword">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        {% if user.id is  None %}
                            <div class="widget-header">
                                <small class="title text-muted new-font" style="text-align: right"> سلام کاربر
                                    عزیز </small>
                                <div>
                                    <a href="{% url 'account:login' %}" class="new-font">ورود</a> <span
                                        class="dark-transp"> | </span>
                                    <a href="{% url 'account:register' %}" class="new-font"> ثبت نام</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="widget-header">
                                <small class="title text-muted new-font"> سلام {{ user.first_name }}</small>
                                <div>
                                    <a href="{% url 'account:dashboard' %}" class="new-font">داشبورد</a> <span
                                        class="dark-transp"> | </span>
                                    <a href="{% url 'account:logout' %}" class="new-font"> خروج</a>
                                </div>
                            </div>
                        {% endif %}
                        <a href="{% url 'carts:cart' %}" class="widget-header pl-3 ml-3">
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{ cart_count }}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- container.// -->
    </section> <!-- header-main .// -->

    <script>
        $(document).ready(function () {
            $('.thumb a').click(function (e) {
                e.preventDefault();
                $('.main-image img').attr('src', $(this).attr("href"));
            })
        })
    </script>
</header> <!-- section-header.// -->



{% block content %}

{% endblock %}


</body>
</html>

templates/base/navbar.html
{% load static %}
<aside class="col-md-3 new-font">
    <!--   SIDEBAR   -->
    <ul class="list-group" style="text-align: right;">
        <a class="list-group-item  {% if '/account/' == request.path %} active {% endif %}"
           href="{% url 'account:dashboard' %}"> داشبورد </a>
        <a class="list-group-item  {% if '/my_orders/' in request.path %} active {% endif %}"
           href="{% url 'account:my_orders' %}"> خرید های من </a>
        <a class="list-group-item  {% if '/edit_profile/' in request.path %} active {% endif %}"
           href="{% url 'account:edit_profile' %}"> ویرایش پروفایل </a>
        <a class="list-group-item   {% if '/change_password/' in request.path %} active {% endif %}"
           href="{% url 'account:change_password' %}"> تغییر رمز عبور </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'account:logout' %}"> <i class="fa fa-power-off"></i> <span
            class="text"> خروج </span> </a>
    <!--   SIDEBAR .//END   -->
</aside>