accounts/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('reset_password_validate/<uidb64>/<token>/', views.reset_password_validate, name='reset_password_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
]

ads/urls.py
from django.urls import path
from . import views

app_name = 'ad'

urlpatterns = [
    path('', views.ads, name='ads'),
    path('ads_detail/<slug:ads_slug>/', views.ads_detail, name='ads_detail'),
]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'
urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

greatkart/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('account/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('ads/', include('ads.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

store/models.py
from django.db import models
from django.urls import reverse

from accounts.models import Account
from category.models import Category
from django.utils.html import format_html


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True, verbose_name='نام محصول ')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='محصول')
    description = models.TextField(max_length=500, verbose_name='توضیحات')
    price = models.IntegerField(verbose_name='قیمت')
    image = models.ImageField(upload_to='photos/products', verbose_name='تصویر')
    stock = models.IntegerField(verbose_name='تعداد موجودی')
    is_available = models.BooleanField(default=True, verbose_name='وضعیت')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='دسته بندی')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    modified_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بروزرسانی')

    class Meta:
        verbose_name = 'محصولات'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.product_name

    # def averageReview(self):
    #     reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
    #     avg = 0
    #     if reviews['average'] is not None:
    #         avg = float(reviews['average'])
    #     return avg
    #
    # def countReview(self):
    #     reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
    #     count = 0
    #     if reviews['count'] is not None:
    #         count = int(reviews['count'])
    #     return count

    def get_url(self):
        return reverse('store:product_detail', args=[self.category.slug, self.slug])

    def img(self):
        return format_html('<img src="{}" height="50" style="border-radius:50px;"/>'.format(self.image.url))


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    variation_value = models.CharField(blank=True, null=True, max_length=100, default='test', verbose_name='مقدار')
    is_active = models.BooleanField(default=True, verbose_name='وضعیت')
    created_date = models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')

    def __str__(self):
        return self.variation_value

    class Meta:
        verbose_name = 'تغییرات و مقدار'
        verbose_name_plural = 'تغییرات و مقدار'


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='محصول')
    user = models.ForeignKey(Account, on_delete=models.CASCADE, verbose_name='کاربر')
    subject = models.CharField(max_length=100, blank=True, verbose_name='عنوان')
    review = models.TextField(max_length=500, blank=True, verbose_name='نظر')
    ip = models.CharField(max_length=20, blank=True, verbose_name='ادرس ip')
    status = models.BooleanField(default=True, verbose_name='وضعیت')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'نظر و امتیاز ها'
        verbose_name_plural = 'نظر و امتیاز ها'


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE, verbose_name='محصول')
    image = models.ImageField(upload_to='photos/products', max_length=255, verbose_name='تصویر')

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'گالری تصاویر'
        verbose_name_plural = 'گالری تصاویر'

    def img(self):
        return format_html('<img src="{}" height="50" style="border-radius:50px;"/>'.format(self.image.url))

store/forms.py
from django import forms
from .models import ReviewRating


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review']

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from carts.models import CartItem
from store.forms import ReviewForm
from store.models import Product, ReviewRating, ProductGallery
from category.models import Category
from carts.views import _cart_id
from django.core.paginator import Paginator
from django.db.models import Q


def store(request, category_slug=None):
    categories = None
    products = None

    if category_slug is not None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        products_count = products.count()

    context = {
        'products': paged_products,
        'products_count': products_count,

    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        raise e
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)
    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'reviews': reviews,
        'product_gallery': product_gallery,
    }
    return render(request, 'store/product-detail.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) |
                                                                        Q(product_name__icontains=keyword))
            products_count = products.count()

    context = {
        'products': products,
        'products_count': products_count,
    }
    return render(request, 'store/store.html', context)


def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'نظر شما با موفقیت بروزرسانی شد.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                messages.success(request, 'نظر شما با موفقیت ثبت شد.')
                return redirect(url)

templates/store/product-detail.html
{% extends 'base/base.html' %}
{% load humanize %}
{% load persian_number %}
{% block title %} جزئیات محصول  |  تک کا مارکت {% endblock %}
{% load jalali_tags %}
{% block content %}
    <section class="section-content padding-y bg new-font" style="direction: rtl; text-align: right;">
        <div class="container">

            <!-- ============================ COMPONENT 1 ================================= -->
            <div class="card">
                <div class="row no-gutters">
                    <aside class="col-md-6">
                        <article class="gallery-wrap">
                            <div class="img-big-wrap main-image">
                                <div style="text-align: center;"><img src="{{ single_product.image.url }}"></div>
                            </div> <!-- img-big-wrap.// -->
                            <ul class="thumb">
                                <li>
                                    <a href="{{ single_product.image.url }}" target="main-image"><img
                                            src="{{ single_product.image.url }}"
                                            alt="Product Image"></a>
                                    {% for img in product_gallery %}
                                        <a href="{{ img.image.url }}" target="main-image"><img src="{{ img.image.url }}"
                                                                                               alt="Product Image"></a>
                                    {% endfor %}
                                </li>

                            </ul>
                        </article>
                    </aside>
                    <main class="col-md-6 border-left">
                        <form action="{% url 'carts:add_cart' single_product.id %}" method="post">
                            {% csrf_token %}
                            <article class="content-body">

                                <h2 class="title">{{ single_product.product_name |   persianize_digits  }}</h2>
                                <br>
                                <div class="mb-3">
                                    <var class="price h4 new-font">  قیمت : {{ single_product.price | persian_int | intcomma:False }} تومان  </var>
                                </div>
                                <br>
                                <p class="new-font">{{ single_product.description | linebreaks }}</p>
                                <br>
                                <hr>
                                {% if single_product.stock <= 0 %}
                                    <h5 class="new-font"> اتمام موجودی </h5>
                                {% else %}
                                    <button type="submit"
                                            class="btn  btn-primary"> <span
                                            class="text new-font"> افزودن به سبد خرید </span> <i
                                            class="fas fa-shopping-cart"></i>
                                    </button>
                                {% endif %}

                            </article> <!-- product-info-aside .// -->
                        </form>
                    </main> <!-- col.// -->
                </div> <!-- row.// -->
            </div> <!-- card.// -->
            <!-- ============================ COMPONENT 1 END .// ================================= -->

            <br>

            <div class="row">
                <div class="col-md-9">


                    <form action="{% url 'store:submit_review' single_product.id %}" method="POST">
                        {% csrf_token %}
                        <h5 class="new-font"> لطفا نظر خود را بنویسید </h5>

                        <div class="new-font">
                            <!-- Rating stars -->
                            <label> شما به این محصول چه امتیازی میدید؟ </label>
                            <br>
                            <br>
                            عنوان:
                            <br><br>
                            <input type="text" class="form-control" name="subject" required>
                            <br>
                            نظر:
                            <br><br>
                            <textarea name="review" rows="4" class="form-control" required></textarea>
                            <br>
                            {% if user.is_authenticated %}
                                <input type="submit" value="تایید" class="btn btn-primary">
                            {% else %}
                                <p> لطفا واردشوید/ ثبت نام کنید <span><a
                                        href="{% url 'account:login' %}"> ورود </a></span></p>

                            {% endif %}

                        </div>
                        {% include 'base/alert.html' %}
                    </form>
                    <br>
                    <header class="section-heading">
                        <h3 class="new-font">نظرات </h3>
                    </header>

                    {% for review in reviews %}
                        <article class="box mb-3">
                            <div class="icontext w-100">

                                <div class="text">
                                    <h6 class="mb-1 new-font">{{ review.user.full_name }} </h6>
                                    <span class="date text-muted float-md-right new-font">{{ review.updated_at | to_jalali:'%y/%m/%d _ %H:%M:%S' }} </span>

                                </div>
                            </div> <!-- icontext.// -->
                            <div class="mt-3 new-font">
                                <h6>{{ review.subject }}</h6>
                                <p>
                                    {{ review.review }}
                                </p>
                            </div>
                        </article>
                    {% endfor %}


                </div> <!-- col.// -->
            </div>


        </div> <!-- container .//  -->
    </section>
{% endblock %}